// Copyright (c) Alexander Bocharov. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Text;

namespace ABForge.Xml.Tests;

public class XmlConvertTests
{
    [Fact]
    public void Serialize_WithSerializer_ReturnsExpectedXml()
    {
        // Arrange
        var value = new TestObject { Name = "John", Age = 30 };
        // In real project, this would be generated by your Source Generator
        var serializer = new TestObjectXmlSerializer();

        // Act
        var result = XmlConvert.Serialize(value, serializer);

        // Assert
        Assert.NotNull(result);
        var xml = Encoding.UTF8.GetString(result);
        Assert.Contains("<Name>John</Name>", xml);
        Assert.Contains("<Age>30</Age>", xml);
    }

    [Fact]
    public void Deserialize_WithSerializer_ReturnsObject()
    {
        // Arrange
        var xml = "<TestObject><Name>Jane</Name><Age>25</Age></TestObject>";
        var bytes = Encoding.UTF8.GetBytes(xml);
        var serializer = new TestObjectXmlSerializer();

        // Act
        var result = XmlConvert.Deserialize(bytes.AsSpan(), serializer);

        // Assert
        Assert.NotNull(result);
        Assert.Equal("Jane", result.Name);
        Assert.Equal(25, result.Age);
    }

    [Fact]
    public void Serialize_ClassicApi_StillWorks()
    {
        // Arrange
        var value = new TestObject { Name = "Classic", Age = 50 };

        // Act
#pragma warning disable MSML001 // Suppression for AOT-incompatible call if needed
        var result = XmlConvert.Serialize(value);
#pragma warning restore MSML001

        // Assert
        Assert.NotNull(result);
        Assert.Contains("Classic", Encoding.UTF8.GetString(result));
    }

    [Fact]
    public void Deserialize_EmptySpan_ReturnsDefault()
    {
        // Arrange
        ReadOnlySpan<byte> emptySpan = ReadOnlySpan<byte>.Empty;
        var serializer = new TestObjectXmlSerializer();

        // Act
        var result = XmlConvert.Deserialize(emptySpan, serializer);

        // Assert
        Assert.Null(result);
    }

    // --- Mock of Generated Serializer ---
    // In actual usage, this is produced by the [GenerateXmlSerializer] attribute
    private sealed class TestObjectXmlSerializer : IXmlSerializer<TestObject>
    {
        public void WriteXml(System.Xml.XmlWriter writer, TestObject value)
        {
            writer.WriteStartElement(nameof(TestObject));
            writer.WriteElementString(nameof(TestObject.Name), value.Name);
            writer.WriteElementString(nameof(TestObject.Age), value.Age.ToString());
            writer.WriteEndElement();
        }

        public TestObject? ReadXml(System.Xml.XmlReader reader)
        {
            if (!reader.IsStartElement(nameof(TestObject))) return null;

            reader.ReadStartElement();
            var name = reader.ReadElementContentAsString(nameof(TestObject.Name), "");
            var age = reader.ReadElementContentAsInt(nameof(TestObject.Age), "");
            reader.ReadEndElement();

            return new TestObject { Name = name, Age = age };
        }
    }

    public class TestObject
    {
        public required string Name { get; set; }
        public required int Age { get; set; }
    }
}
