// Copyright (c) Alexander Bocharov. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ABForge.Xml.Generators;

/// <summary>
/// Incremental generator that produces highly optimized, allocation-free XML serializers.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class XmlSerializerGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typesToGenerate = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(typesToGenerate, static (spc, source) => Execute(spc, source!));
    }

    private static ITypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.Node;
        foreach (var attributeList in typeDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (context.SemanticModel.GetSymbolInfo(attribute).Symbol is not IMethodSymbol attributeSymbol)
                {
                    continue;
                }

                var attributeFullName = attributeSymbol.ContainingType.ToDisplayString();
                if (attributeFullName == "ABForge.Xml.GenerateXmlSerializerAttribute")
                {
                    return context.SemanticModel.GetDeclaredSymbol(typeDeclaration) as ITypeSymbol;
                }
            }
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, ITypeSymbol typeSymbol)
    {
        var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        var typeName = typeSymbol.Name;
        var className = $"{typeName}XmlSerializer";

        var properties = typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .ToImmutableArray();

        var source = GenerateSerializerCode(namespaceName, typeName, className, properties);
        context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSerializerCode(string ns, string typeName, string className, ImmutableArray<IPropertySymbol> properties)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Xml;");
        sb.AppendLine("using ABForge.Xml;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("/// <summary> Automatically generated AOT-safe XML serializer for <see cref=\"").Append(typeName).AppendLine("\"/>. </summary>");
        sb.Append("public sealed class ").Append(className).Append(" : IXmlSerializer<").Append(typeName).AppendLine(">");
        sb.AppendLine("{");

        // WriteXml Method
        sb.Append("    public void WriteXml(XmlWriter writer, ").Append(typeName).AppendLine(" value)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(writer);");
        sb.AppendLine();
        sb.AppendLine("        if (value == null)");
        sb.AppendLine("        {");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.Append("        writer.WriteStartElement(\"").Append(typeName).AppendLine("\");");

        foreach (var prop in properties)
        {
            sb.Append("        writer.WriteElementString(\"").Append(prop.Name).Append("\", value.").Append(prop.Name).AppendLine("?.ToString() ?? string.Empty);");
        }

        sb.AppendLine("        writer.WriteEndElement();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ReadXml Method
        sb.Append("    public ").Append(typeName).AppendLine(" ReadXml(XmlReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(reader);");
        sb.Append("        var result = new ").Append(typeName).AppendLine("();");
        sb.AppendLine();
        sb.AppendLine("        if (reader.IsEmptyElement)");
        sb.AppendLine("        {");
        sb.AppendLine("            reader.Read();");
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.Append("        reader.ReadStartElement(\"").Append(typeName).AppendLine("\");");
        sb.AppendLine();
        sb.AppendLine("        while (reader.NodeType != XmlNodeType.EndElement)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (reader.NodeType == XmlNodeType.Element)");
        sb.AppendLine("            {");
        sb.AppendLine("                string localName = reader.LocalName;");
        sb.AppendLine("                reader.Read(); // Move to content");
        sb.AppendLine();
        sb.AppendLine("                if (reader.NodeType == XmlNodeType.Text || reader.NodeType == XmlNodeType.CDATA)");
        sb.AppendLine("                {");
        sb.AppendLine("                    ReadOnlySpan<char> content = reader.ValueSpan;");
        sb.AppendLine();
        sb.AppendLine("                    switch (localName)");
        sb.AppendLine("                    {");

        foreach (var prop in properties)
        {
            string typeNameStr = prop.Type.ToDisplayString();
            string parseMethod = typeNameStr switch
            {
                "string" => "content.ToString()",
                "int" => "int.Parse(content)",
                "long" => "long.Parse(content)",
                "bool" => "bool.Parse(content)",
                "double" => "double.Parse(content)",
                "System.DateTime" => "DateTime.Parse(content)",
                _ => "default"
            };
            sb.Append("                        case \"").Append(prop.Name).Append("\": result.").Append(prop.Name).Append(" = ").Append(parseMethod).AppendLine("; break;");
        }

        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                if (reader.NodeType != XmlNodeType.EndElement)");
        sb.AppendLine("                {");
        sb.AppendLine("                    reader.Skip();");
        sb.AppendLine("                }");
        sb.AppendLine("                else");
        sb.AppendLine("                {");
        sb.AppendLine("                    reader.ReadEndElement();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine("                reader.Read();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        reader.ReadEndElement();");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
